### ISSUE TITLE
Server crashes when polymer/.force_autohost already exists

### ISSUE THREAD

**Issue by Zekiu** [tomalbrc/toms-mobs#1]
Log:
```
[17:57:54] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[17:57:54] [ForkJoinPool-1-worker-2/WARN]: Mod io_netty_netty-codec-socks uses the version 4.1.97.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:57:54] [ForkJoinPool-1-worker-2/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.97.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:57:54] [ForkJoinPool-1-worker-2/WARN]: Mod io_netty_netty-handler-proxy uses the version 4.1.97.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:57:54] [ForkJoinPool-1-worker-3/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:57:54] [main/INFO]: Loading 67 mods:
	- cc-tweaked-polymer-patch 1.109.6.0+1.20.4
	   |-- factorytools 0.1.8+1.20.4
	   |-- map-canvas-api 0.2.2+1.19.4
	   |-- player-data-api 0.4.0+1.20.3
	   \-- sgui 1.4.1+1.20.4
	- computercraft 1.110.2
	   |-- cc_tweaked_cobalt 0.9.2
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   |-- com_jcraft_jzlib 1.1.3
	   |-- io_netty_netty-codec-http 4.1.97.Final
	   |-- io_netty_netty-codec-socks 4.1.97.Final
	   \-- io_netty_netty-handler-proxy 4.1.97.Final
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.20.4
	- polymer-bundled 0.7.7+1.20.4
	   |-- polymer-autohost 0.7.7+1.20.4
	   |-- polymer-blocks 0.7.7+1.20.4
	   |-- polymer-common 0.7.7+1.20.4
	   |    \-- packet_tweaker 0.5.1+1.20.4
	   |-- polymer-core 0.7.7+1.20.4
	   |    |-- polymer-networking 0.7.7+1.20.4
	   |    |    \-- polymer-common 0.7.7+1.20.4
	   |    |         \-- packet_tweaker 0.5.1+1.20.4
	   |    \-- polymer-registry-sync-manipulator 0.7.7+1.20.4
	   |-- polymer-resource-pack 0.7.7+1.20.4
	   |    \-- polymer-common 0.7.7+1.20.4
	   |         \-- packet_tweaker 0.5.1+1.20.4
	   \-- polymer-virtual-entity 0.7.7+1.20.4
	        \-- polymer-common 0.7.7+1.20.4
	             \-- packet_tweaker 0.5.1+1.20.4
	- toms_mobs 1.2.1+1.20.4
	   \-- bil 1.1.6
[17:57:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/mnt/dysk/minecraft/gfdjgh/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:57:54] [main/INFO]: Compatibility level set to JAVA_17
[17:57:55] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[17:58:04] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'toms_mobs'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: ./polymer/.force_autohost
	at de.tomalbrc.toms_mobs.TomsMobs.forceAutohost(TomsMobs.java:33) ~[toms_mobs-1.2.1+1.20.4.jar:?]
	at de.tomalbrc.toms_mobs.TomsMobs.onInitialize(TomsMobs.java:18) ~[toms_mobs-1.2.1+1.20.4.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	... 7 more
Caused by: java.nio.file.FileAlreadyExistsException: ./polymer/.force_autohost
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.createFile(Files.java:658) ~[?:?]
	at de.tomalbrc.toms_mobs.TomsMobs.forceAutohost(TomsMobs.java:31) ~[toms_mobs-1.2.1+1.20.4.jar:?]
	at de.tomalbrc.toms_mobs.TomsMobs.onInitialize(TomsMobs.java:18) ~[toms_mobs-1.2.1+1.20.4.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	... 7 more

```

**Comment by tomalbrc** [comment]
Thanks for the report, I just updated the mod to 1.2.2, it should fix the crash
