### ISSUE TITLE
Trying to fix Mod Compat with new performance Mod "Async"

### ISSUE THREAD

**Issue by suerion** [tomalbrc/toms-mobs#4]
Hey, i trying to fix issues with Async performance Mod on Fabric 1.21.1 with 0.16.7
Windows 11
Java 21

You could look on the Issue and the latest Log
https://github.com/AxalotLDev/Async/issues/1

Will look tomorow on more test for the issues

**Comment by Tunga-Tech** [comment]
I have this same problem: `[Server thread/ERROR]: Error ticking entity translation{key='entity.toms_mobs.butterfly', args=[]} synchronously                                                                                                                     java.lang.ClassCastException: class net.minecraft.world.chunk.WrapperProtoChunk cannot be cast to class net.minecraft.world.chunk.WorldChunk (net.minecraft.world.chunk.WrapperProtoChunk and net.minecraft.world.chunk.WorldChunk are in unnamed module of loader 'knot' @3ffc5af1)
        at knot//MC/net.minecraft.world.World.getChunk(World.java:202) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.world.World.getBlockState(World.java:11086) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.LivingEntity.travel(LivingEntity.java:2320) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:2824) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:572) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity.java:128) ~[server-intermediar
y.jar:?]
        at knot//MC/net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity.java:57) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2507) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:770) ~[server-intermediary.jar:?]
        at knot/com.axalotl.async.ParallelProcessor.tickSynchronously(ParallelProcessor.java:106) ~[async-0.1.3+alpha.1-1.21.1.jar:?]
        at knot/com.axalotl.async.ParallelProcessor.callEntityTick(ParallelProcessor.java:76) ~[async-0.1.3+alpha.1-1.21.1.jar:?]
        at knot//MC/net.minecraft.server.world.ServerWorld.redirect$zih000$async$overwriteEntityTicking(ServerWorld.java:19789) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.world.EntityList.forEach(EntityList.java:54) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:372) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
        at knot//MC/net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:299) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by tomalbrc** [comment]
I won't add support for some obscure poorly written "performance optimisation" mod
